apiVersion: v1
kind: Namespace
metadata:
  name: pacman-app
  labels:
    app: pacman-app
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: mongodb-primary-cluster
  namespace: pacman-app
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values: 
          - mongodb-primary-cluster
---
apiVersion: v1                      
kind: Namespace
metadata:
  name: ggithubcom-waynedovey-mongodb-cluster-ns
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  annotations:
    apps.open-cluster-management.io/reconcile-rate: medium
  name: ggithubcom-waynedovey-mongodb-cluster
  namespace: ggithubcom-waynedovey-mongodb-cluster-ns
spec:
  type: Git
  pathname: 'https://github.com/waynedovey/mongodb-cluster.git'
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: primary
    apps.open-cluster-management.io/git-path: deploy
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: mongodb-primary-cluster
  name: mongodb-primary-cluster-subscription-1
  namespace: pacman-app
spec:
  channel: ggithubcom-waynedovey-mongodb-cluster-ns/ggithubcom-waynedovey-mongodb-cluster
  placement:
    placementRef:
      kind: PlacementRule
      name: mongodb-primary-cluster-placement-1
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: mongodb-primary-cluster
  name: mongodb-primary-cluster-placement-1
  namespace: pacman-app
spec:
  clusterSelector:
    matchLabels:
      'environment': 'dev'
      'apps/pacman': 'deployed'
      'mongodb': 'primary'
