apiVersion: v1
kind: Namespace
metadata:
  name: mongodb-cluster
  labels:
    app: mongodb-cluster
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: mongodb-secondary-cluster
  namespace: mongodb-cluster
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values: 
          - mongodb-secondary-cluster
---
apiVersion: v1                      
kind: Namespace
metadata:
  name: mongodb-cluster-ns
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  annotations:
    apps.open-cluster-management.io/reconcile-rate: medium
  name: mongodb-cluster
  namespace: mongodb-cluster-ns
spec:
  type: Git
  pathname: 'https://github.com/waynedovey/mongodb-cluster.git'
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: secondary-cluster
    apps.open-cluster-management.io/git-path: deploy
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: mongodb-secondary-cluster
  name: mongodb-secondary-cluster-subscription-1
  namespace: mongodb-cluster
spec:
  channel: mongodb-cluster-ns/mongodb-cluster
  placement:
    placementRef:
      kind: PlacementRule
      name: mongodb-secondary-cluster-placement-1
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: mongodb-secondary-cluster
  name: mongodb-secondary-cluster-placement-1
  namespace: mongodb-cluster
spec:
  clusterSelector:
    matchLabels:
      #'environment': 'dev'
      #'apps/pacman': 'deployed'
      'mongodb': 'secondary'
