apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo4
spec:
  selector:
    matchLabels:
      app: mongo4
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo4
    spec:
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: mongo4-pvc
      terminationGracePeriodSeconds: 10
      containers:
      - name: mongo
        image: mongo
        command:
        - mongod
        - "--bind_ip_all"
        - "--replSet"
        - rs0
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
